---
abstract: 'PSGI/Plack plugin for Padre'
author:
  - 'Patrick Donelan <pdonelan@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Locale::Msgfmt: 0.14
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.94'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Padre-Plugin-Plack
no_index:
  directory:
    - inc
    - share
    - t
requires:
  File::Basename: 0
  File::Find::Rule: 0
  File::Which: 0
  Padre: 0.53
  Plack: 0.9021
  Proc::Killfam: 0
  Scalar::Util: 0
resources:
  homepage: http://padre.perlide.org/
  license: http://dev.perl.org/licenses/
  repository: http://svn.perlide.org/padre/trunk/Padre-Plugin-Plack
version: 0.04
